// Auto-generated from Minecraft 1.20 zh_cn.json
export const blockMeta: Record<string, { nbt: string | null; zh: string | null }> = {
  "Grass Block": { nbt: "grass_block", zh: "草方块" },
  "Slime Block": { nbt: "slime_block", zh: "黏液块" },
  "Sand": { nbt: "sand", zh: "沙子" },
  "Sandstone": { nbt: "sandstone", zh: "砂岩" },
  "Sandstone Slab": { nbt: "sandstone_slab", zh: "砂岩台阶" },
  "Birch Log (vertical)": { nbt: "birch_log", zh: "白桦原木" },
  "Birch Planks": { nbt: "birch_planks", zh: "白桦木板" },
  "Birch Slab": { nbt: "birch_slab", zh: "白桦木台阶" },
  "Glowstone": { nbt: "glowstone", zh: "荧石" },
  "End Stone": { nbt: "end_stone", zh: "末地石" },
  "End Stone Bricks": { nbt: "end_stone_bricks", zh: "末地石砖" },
  "End Stone Brick Slab": { nbt: "end_stone_brick_slab", zh: "末地石砖台阶" },
  "Bone Block": { nbt: "bone_block", zh: "骨块" },
  "Birch Pressure Plate": { nbt: "birch_pressure_plate", zh: "白桦木压力板" },
  "Ochre Froglight": { nbt: "ochre_froglight", zh: "赭黄蛙明灯" },
  "Cobweb": { nbt: "cobweb", zh: "蜘蛛网" },
  "Mushroom Stem": { nbt: "mushroom_stem", zh: "蘑菇柄" },
  "White Candle": { nbt: "white_candle", zh: "白色蜡烛" },
  "TNT": { nbt: "tnt", zh: "TNT" },
  "Block of Redstone": { nbt: "redstone_block", zh: "红石块" },
  "Ice": { nbt: "ice", zh: "冰" },
  "Packed Ice": { nbt: "packed_ice", zh: "浮冰" },
  "Blue Ice": { nbt: "blue_ice", zh: "蓝冰" },
  "Block of Iron": { nbt: "iron_block", zh: "铁块" },
  "Iron Trapdoor": { nbt: "iron_trapdoor", zh: "铁活板门" },
  "Iron Bars": { nbt: null, zh: null },
  "Weighted Pressure Plate (Heavy)": { nbt: "heavy_weighted_pressure_plate", zh: "重质测重压力板" },
  "Brewing Stand": { nbt: "brewing_stand", zh: "酿造台" },
  "Leaves (Oak)": { nbt: "oak_leaves", zh: "橡树树叶" },
  "Leaves (Spruce)": { nbt: "spruce_leaves", zh: "云杉树叶" },
  "Leaves (Birch)": { nbt: "birch_leaves", zh: "白桦树叶" },
  "Leaves (Jungle)": { nbt: "jungle_leaves", zh: "丛林树叶" },
  "Leaves (Acacia)": { nbt: "acacia_leaves", zh: "金合欢树叶" },
  "Leaves (Dark Oak)": { nbt: "dark_oak_leaves", zh: "深色橡树树叶" },
  "Leaves (Azalea)": { nbt: "azalea_leaves", zh: "杜鹃树叶" },
  "Block of Bamboo (horizontal)": { nbt: "bamboo_block", zh: "竹块" },
  "Clay": { nbt: "clay", zh: "黏土块" },
  "Jungle Log (vertical)": { nbt: "jungle_log", zh: "丛林原木" },
  "Jungle Planks": { nbt: "jungle_planks", zh: "丛林木板" },
  "Jungle Slab": { nbt: "jungle_slab", zh: "丛林木台阶" },
  "Dirt": { nbt: "dirt", zh: "泥土" },
  "Coarse Dirt": { nbt: "coarse_dirt", zh: "砂土" },
  "Rooted Dirt": { nbt: "rooted_dirt", zh: "缠根泥土" },
  "Jukebox": { nbt: "jukebox", zh: "唱片机" },
  "Granite": { nbt: "granite", zh: "花岗岩" },
  "Granite Slab": { nbt: "granite_slab", zh: "花岗岩台阶" },
  "Jungle Pressure Plate": { nbt: "jungle_pressure_plate", zh: "丛林木压力板" },
  "Packed Mud": { nbt: "packed_mud", zh: "泥坯" },
  "Cobblestone": { nbt: "cobblestone", zh: "圆石" },
  "Cobblestone Slab": { nbt: "cobblestone_slab", zh: "圆石台阶" },
  "Mossy Cobblestone": { nbt: "mossy_cobblestone", zh: "苔石" },
  "Mossy Cobblestone Slab": { nbt: "mossy_cobblestone_slab", zh: "苔石台阶" },
  "Stone": { nbt: "stone", zh: "石头" },
  "Stone Slab": { nbt: "stone_slab", zh: "石头台阶" },
  "Smooth Stone Slab": { nbt: "smooth_stone_slab", zh: "平滑石头台阶" },
  "Stone Bricks": { nbt: "stone_bricks", zh: "石砖" },
  "Stone Brick Slab": { nbt: "stone_brick_slab", zh: "石砖台阶" },
  "Andesite": { nbt: "andesite", zh: "安山岩" },
  "Andesite Slab": { nbt: "andesite_slab", zh: "安山岩台阶" },
  "Bedrock": { nbt: "bedrock", zh: "基岩" },
  "Acacia Log (horizontal)": { nbt: "acacia_log", zh: "金合欢原木" },
  "Gravel": { nbt: "gravel", zh: "沙砾" },
  "Stone Pressure Plate": { nbt: "stone_pressure_plate", zh: "石头压力板" },
  "Water (Unsupported!)": { nbt: "water", zh: "水" },
  "Oak Log (vertical)": { nbt: "oak_log", zh: "橡木原木" },
  "Oak Planks": { nbt: "oak_planks", zh: "橡木木板" },
  "Oak Slab": { nbt: "oak_slab", zh: "橡木台阶" },
  "Crafting Table": { nbt: "crafting_table", zh: "工作台" },
  "Oak Pressure Plate": { nbt: "oak_pressure_plate", zh: "橡木压力板" },
  "Birch Log (horizontal)": { nbt: "birch_log", zh: "白桦原木" },
  "Diorite": { nbt: "diorite", zh: "闪长岩" },
  "Diorite Slab": { nbt: "diorite_slab", zh: "闪长岩台阶" },
  "Quartz Block": { nbt: "quartz_block", zh: "石英块" },
  "Quartz Slab": { nbt: "quartz_slab", zh: "石英台阶" },
  "Sea Lantern": { nbt: "sea_lantern", zh: "海晶灯" },
  "White Wool": { nbt: "white_wool", zh: "白色羊毛" },
  "White Carpet": { nbt: "white_carpet", zh: "白色地毯" },
  "White Stained Glass": { nbt: "white_stained_glass", zh: "白色染色玻璃" },
  "White Concrete": { nbt: "white_concrete", zh: "白色混凝土" },
  "White Concrete Powder": { nbt: "white_concrete_powder", zh: "白色混凝土粉末" },
  "White Glazed Terracotta": { nbt: "white_glazed_terracotta", zh: "白色带釉陶瓦" },
  "Snow Block": { nbt: "snow_block", zh: "雪块" },
  "Snow Layer": { nbt: "snow", zh: "雪" },
  "Orange Wool": { nbt: "orange_wool", zh: "橙色羊毛" },
  "Orange Carpet": { nbt: "orange_carpet", zh: "橙色地毯" },
  "Orange Stained Glass": { nbt: "orange_stained_glass", zh: "橙色染色玻璃" },
  "Orange Concrete": { nbt: "orange_concrete", zh: "橙色混凝土" },
  "Orange Concrete Powder": { nbt: "orange_concrete_powder", zh: "橙色混凝土粉末" },
  "Orange Glazed Terracotta": { nbt: "orange_glazed_terracotta", zh: "橙色带釉陶瓦" },
  "Pumpkin": { nbt: "pumpkin", zh: "南瓜" },
  "Acacia Log (vertical)": { nbt: "acacia_log", zh: "金合欢原木" },
  "Acacia Planks": { nbt: "acacia_planks", zh: "金合欢木板" },
  "Acacia Slab": { nbt: "acacia_slab", zh: "金合欢木台阶" },
  "Red Sand": { nbt: "red_sand", zh: "红沙" },
  "Red Sandstone": { nbt: "red_sandstone", zh: "红砂岩" },
  "Red Sandstone Slab": { nbt: "red_sandstone_slab", zh: "红砂岩台阶" },
  "Terracotta": { nbt: "terracotta", zh: "陶瓦" },
  "Honey Block": { nbt: "honey_block", zh: "蜂蜜块" },
  "Honeycomb Block": { nbt: "honeycomb_block", zh: "蜜脾块" },
  "Block Of Raw Copper": { nbt: "raw_copper_block", zh: "粗铜块" },
  "Waxed Block Of Copper": { nbt: "waxed_copper_block", zh: "涂蜡铜块" },
  "Waxed Cut Copper Slab": { nbt: "waxed_cut_copper_slab", zh: "涂蜡切制铜台阶" },
  "Acacia Pressure Plate": { nbt: "acacia_pressure_plate", zh: "金合欢木压力板" },
  "Magenta Wool": { nbt: "magenta_wool", zh: "品红色羊毛" },
  "Magenta Carpet": { nbt: "magenta_carpet", zh: "品红色地毯" },
  "Magenta Stained Glass": { nbt: "magenta_stained_glass", zh: "品红色染色玻璃" },
  "Magenta Concrete": { nbt: "magenta_concrete", zh: "品红色混凝土" },
  "Magenta Concrete Powder": { nbt: "magenta_concrete_powder", zh: "品红色混凝土粉末" },
  "Magenta Glazed Terracotta": { nbt: "magenta_glazed_terracotta", zh: "品红色带釉陶瓦" },
  "Purpur Block": { nbt: "purpur_block", zh: "紫珀块" },
  "Purpur Slab": { nbt: "purpur_slab", zh: "紫珀台阶" },
  "Light Blue Wool": { nbt: "light_blue_wool", zh: "淡蓝色羊毛" },
  "Light Blue Carpet": { nbt: "light_blue_carpet", zh: "淡蓝色地毯" },
  "Light Blue Stained Glass": { nbt: "light_blue_stained_glass", zh: "淡蓝色染色玻璃" },
  "Light Blue Concrete": { nbt: "light_blue_concrete", zh: "淡蓝色混凝土" },
  "Light Blue Concrete Powder": { nbt: "light_blue_concrete_powder", zh: "淡蓝色混凝土粉末" },
  "Light Blue Glazed Terracotta": { nbt: "light_blue_glazed_terracotta", zh: "淡蓝色带釉陶瓦" },
  "Yellow Wool": { nbt: "yellow_wool", zh: "黄色羊毛" },
  "Yellow Carpet": { nbt: "yellow_carpet", zh: "黄色地毯" },
  "Yellow Stained Glass": { nbt: "yellow_stained_glass", zh: "黄色染色玻璃" },
  "Yellow Concrete": { nbt: "yellow_concrete", zh: "黄色混凝土" },
  "Yellow Concrete Powder": { nbt: "yellow_concrete_powder", zh: "黄色混凝土粉末" },
  "Yellow Glazed Terracotta": { nbt: "yellow_glazed_terracotta", zh: "黄色带釉陶瓦" },
  "Hay Bale": { nbt: "hay_block", zh: "干草捆" },
  "Sponge (any)": { nbt: "sponge", zh: "海绵" },
  "Block of Bamboo (vertical)": { nbt: "bamboo_block", zh: "竹块" },
  "Bamboo Planks": { nbt: "bamboo_planks", zh: "竹板" },
  "Bamboo Slab": { nbt: "bamboo_slab", zh: "竹台阶" },
  "Bamboo Mosaic": { nbt: "bamboo_mosaic", zh: "竹马赛克" },
  "Bamboo Mosaic Slab": { nbt: "bamboo_mosaic_slab", zh: "竹马赛克台阶" },
  "Bamboo Pressure Plate": { nbt: "bamboo_pressure_plate", zh: "竹压力板" },
  "Lime Wool": { nbt: "lime_wool", zh: "黄绿色羊毛" },
  "Lime Carpet": { nbt: "lime_carpet", zh: "黄绿色地毯" },
  "Lime Stained Glass": { nbt: "lime_stained_glass", zh: "黄绿色染色玻璃" },
  "Lime Concrete": { nbt: "lime_concrete", zh: "黄绿色混凝土" },
  "Lime Concrete Powder": { nbt: "lime_concrete_powder", zh: "黄绿色混凝土粉末" },
  "Lime Glazed Terracotta": { nbt: "lime_glazed_terracotta", zh: "黄绿色带釉陶瓦" },
  "Melon": { nbt: "melon", zh: "西瓜" },
  "Pink Wool": { nbt: "pink_wool", zh: "粉红色羊毛" },
  "Pink Carpet": { nbt: "pink_carpet", zh: "粉红色地毯" },
  "Pink Stained Glass": { nbt: "pink_stained_glass", zh: "粉红色染色玻璃" },
  "Pink Concrete": { nbt: "pink_concrete", zh: "粉红色混凝土" },
  "Pink Concrete Powder": { nbt: "pink_concrete_powder", zh: "粉红色混凝土粉末" },
  "Pink Glazed Terracotta": { nbt: "pink_glazed_terracotta", zh: "粉红色带釉陶瓦" },
  "Pearlescent Froglight": { nbt: "pearlescent_froglight", zh: "珠光蛙明灯" },
  "Cherry Leaves": { nbt: "cherry_leaves", zh: "樱花树叶" },
  "Gray Wool": { nbt: "gray_wool", zh: "灰色羊毛" },
  "Gray Carpet": { nbt: "gray_carpet", zh: "灰色地毯" },
  "Gray Stained Glass": { nbt: "gray_stained_glass", zh: "灰色染色玻璃" },
  "Gray Concrete": { nbt: "gray_concrete", zh: "灰色混凝土" },
  "Gray Concrete Powder": { nbt: "gray_concrete_powder", zh: "灰色混凝土粉末" },
  "Gray Glazed Terracotta": { nbt: "gray_glazed_terracotta", zh: "灰色带釉陶瓦" },
  "Dead Tube Coral Block": { nbt: "dead_tube_coral_block", zh: "失活的管珊瑚块" },
  "Dead Brain Coral Block": { nbt: "dead_brain_coral_block", zh: "失活的脑纹珊瑚块" },
  "Dead Bubble Coral Block": { nbt: "dead_bubble_coral_block", zh: "失活的气泡珊瑚块" },
  "Dead Fire Coral Block": { nbt: "dead_fire_coral_block", zh: "失活的火珊瑚块" },
  "Dead Horn Coral Block": { nbt: "dead_horn_coral_block", zh: "失活的鹿角珊瑚块" },
  "Tinted Glass": { nbt: "tinted_glass", zh: "遮光玻璃" },
  "Light Gray Wool": { nbt: "light_gray_wool", zh: "淡灰色羊毛" },
  "Light Gray Carpet": { nbt: "light_gray_carpet", zh: "淡灰色地毯" },
  "Light Gray Stained Glass": { nbt: "light_gray_stained_glass", zh: "淡灰色染色玻璃" },
  "Light Gray Concrete": { nbt: "light_gray_concrete", zh: "淡灰色混凝土" },
  "Light Gray Concrete Powder": { nbt: "light_gray_concrete_powder", zh: "淡灰色混凝土粉末" },
  "Light Gray Glazed Terracotta": { nbt: "light_gray_glazed_terracotta", zh: "淡灰色带釉陶瓦" },
  "Cyan Wool": { nbt: "cyan_wool", zh: "青色羊毛" },
  "Cyan Carpet": { nbt: "cyan_carpet", zh: "青色地毯" },
  "Cyan Stained Glass": { nbt: "cyan_stained_glass", zh: "青色染色玻璃" },
  "Cyan Concrete": { nbt: "cyan_concrete", zh: "青色混凝土" },
  "Cyan Concrete Powder": { nbt: "cyan_concrete_powder", zh: "青色混凝土粉末" },
  "Cyan Glazed Terracotta": { nbt: "cyan_glazed_terracotta", zh: "青色带釉陶瓦" },
  "Prismarine": { nbt: "prismarine", zh: "海晶石" },
  "Prismarine Slab": { nbt: "prismarine_slab", zh: "海晶石台阶" },
  "Purple Wool": { nbt: "purple_wool", zh: "紫色羊毛" },
  "Purple Carpet": { nbt: "purple_carpet", zh: "紫色地毯" },
  "Purple Stained Glass": { nbt: "purple_stained_glass", zh: "紫色染色玻璃" },
  "Purple Concrete": { nbt: "purple_concrete", zh: "紫色混凝土" },
  "Purple Concrete Powder": { nbt: "purple_concrete_powder", zh: "紫色混凝土粉末" },
  "Purple Glazed Terracotta": { nbt: "purple_glazed_terracotta", zh: "紫色带釉陶瓦" },
  "Mycelium": { nbt: "mycelium", zh: "菌丝体" },
  "Amethyst Block": { nbt: "amethyst_block", zh: "紫水晶块" },
  "Blue Wool": { nbt: "blue_wool", zh: "蓝色羊毛" },
  "Blue Carpet": { nbt: "blue_carpet", zh: "蓝色地毯" },
  "Blue Stained Glass": { nbt: "blue_stained_glass", zh: "蓝色染色玻璃" },
  "Blue Concrete": { nbt: "blue_concrete", zh: "蓝色混凝土" },
  "Blue Concrete Powder": { nbt: "blue_concrete_powder", zh: "蓝色混凝土粉末" },
  "Blue Glazed Terracotta": { nbt: "blue_glazed_terracotta", zh: "蓝色带釉陶瓦" },
  "Brown Wool": { nbt: "brown_wool", zh: "棕色羊毛" },
  "Brown Carpet": { nbt: "brown_carpet", zh: "棕色地毯" },
  "Brown Stained Glass": { nbt: "brown_stained_glass", zh: "棕色染色玻璃" },
  "Brown Concrete": { nbt: "brown_concrete", zh: "棕色混凝土" },
  "Brown Concrete Powder": { nbt: "brown_concrete_powder", zh: "棕色混凝土粉末" },
  "Brown Glazed Terracotta": { nbt: "brown_glazed_terracotta", zh: "棕色带釉陶瓦" },
  "Dark Oak Log (any direction)": { nbt: "dark_oak_log", zh: "深色橡木原木" },
  "Dark Oak Planks": { nbt: "dark_oak_planks", zh: "深色橡木木板" },
  "Dark Oak Slab": { nbt: "dark_oak_slab", zh: "深色橡木台阶" },
  "Spruce Log (horizontal)": { nbt: "spruce_log", zh: "云杉原木" },
  "Soul Sand": { nbt: "soul_sand", zh: "灵魂沙" },
  "Soul Soil": { nbt: "soul_soil", zh: "灵魂土" },
  "Dark Oak Pressure Plate": { nbt: "dark_oak_pressure_plate", zh: "深色橡木压力板" },
  "Green Wool": { nbt: "green_wool", zh: "绿色羊毛" },
  "Green Carpet": { nbt: "green_carpet", zh: "绿色地毯" },
  "Green Stained Glass": { nbt: "green_stained_glass", zh: "绿色染色玻璃" },
  "Green Concrete": { nbt: "green_concrete", zh: "绿色混凝土" },
  "Green Concrete Powder": { nbt: "green_concrete_powder", zh: "绿色混凝土粉末" },
  "Green Glazed Terracotta": { nbt: "green_glazed_terracotta", zh: "绿色带釉陶瓦" },
  "Dried Kelp Block": { nbt: "dried_kelp_block", zh: "干海带块" },
  "Red Wool": { nbt: "red_wool", zh: "红色羊毛" },
  "Red Carpet": { nbt: "red_carpet", zh: "红色地毯" },
  "Red Stained Glass": { nbt: "red_stained_glass", zh: "红色染色玻璃" },
  "Red Concrete": { nbt: "red_concrete", zh: "红色混凝土" },
  "Red Concrete Powder": { nbt: "red_concrete_powder", zh: "红色混凝土粉末" },
  "Red Glazed Terracotta": { nbt: "red_glazed_terracotta", zh: "红色带釉陶瓦" },
  "Bricks": { nbt: "bricks", zh: "红砖块" },
  "Bricks Slab": { nbt: "brick_slab", zh: "红砖台阶" },
  "Nether Wart Block": { nbt: "nether_wart_block", zh: "下界疣块" },
  "Shroomlight": { nbt: "shroomlight", zh: "菌光体" },
  "Mangrove Log (vertical)": { nbt: "mangrove_log", zh: "红树原木" },
  "Mangrove Planks": { nbt: "mangrove_planks", zh: "红树木板" },
  "Mangrove Slab": { nbt: "mangrove_slab", zh: "红树木台阶" },
  "Mangrove Pressure Plate": { nbt: "mangrove_pressure_plate", zh: "红树木压力板" },
  "Black Wool": { nbt: "black_wool", zh: "黑色羊毛" },
  "Black Carpet": { nbt: "black_carpet", zh: "黑色地毯" },
  "Black Stained Glass": { nbt: "black_stained_glass", zh: "黑色染色玻璃" },
  "Black Concrete": { nbt: "black_concrete", zh: "黑色混凝土" },
  "Black Concrete Powder": { nbt: "black_concrete_powder", zh: "黑色混凝土粉末" },
  "Black Glazed Terracotta": { nbt: "black_glazed_terracotta", zh: "黑色带釉陶瓦" },
  "Block of Coal": { nbt: "coal_block", zh: "煤炭块" },
  "Obsidian": { nbt: "obsidian", zh: "黑曜石" },
  "Crying Obsidian": { nbt: "crying_obsidian", zh: "哭泣的黑曜石" },
  "Blackstone": { nbt: "blackstone", zh: "黑石" },
  "Blackstone Slab": { nbt: "blackstone_slab", zh: "黑石台阶" },
  "Basalt": { nbt: "basalt", zh: "玄武岩" },
  "Block Of Netherite": { nbt: "netherite_block", zh: "下界合金块" },
  "Polished Blackstone Pressure Plate": { nbt: "polished_blackstone_pressure_plate", zh: "磨制黑石压力板" },
  "Sculk": { nbt: "sculk", zh: "幽匿块" },
  "Sculk Catalyst": { nbt: "sculk_catalyst", zh: "幽匿催发体" },
  "Sculk Shrieker": { nbt: "sculk_shrieker", zh: "幽匿尖啸体" },
  "Block of Gold": { nbt: "gold_block", zh: "金块" },
  "Weighted Pressure Plate (Light)": { nbt: "light_weighted_pressure_plate", zh: "轻质测重压力板" },
  "Block Of Raw Gold": { nbt: "raw_gold_block", zh: "粗金块" },
  "Block of Diamond": { nbt: "diamond_block", zh: "钻石块" },
  "Prismarine Bricks": { nbt: "prismarine_bricks", zh: "海晶石砖" },
  "Prismarine Brick Slab": { nbt: "prismarine_brick_slab", zh: "海晶石砖台阶" },
  "Dark Prismarine": { nbt: "dark_prismarine", zh: "暗海晶石" },
  "Dark Prismarine Slab": { nbt: "dark_prismarine_slab", zh: "暗海晶石台阶" },
  "Beacon": { nbt: "beacon", zh: "信标" },
  "Lapis Lazuli Block": { nbt: "lapis_block", zh: "青金石块" },
  "Block of Emerald": { nbt: "emerald_block", zh: "绿宝石块" },
  "Spruce Log (vertical)": { nbt: "spruce_log", zh: "云杉原木" },
  "Spruce Planks": { nbt: "spruce_planks", zh: "云杉木板" },
  "Spruce Slab": { nbt: "spruce_slab", zh: "云杉木台阶" },
  "Oak Log (horizontal)": { nbt: "oak_log", zh: "橡木原木" },
  "Jungle Log (horizontal)": { nbt: "jungle_log", zh: "丛林原木" },
  "Podzol": { nbt: "podzol", zh: "灰化土" },
  "Spruce Pressure Plate": { nbt: "spruce_pressure_plate", zh: "云杉木压力板" },
  "Mangrove Log (horizontal)": { nbt: "mangrove_log", zh: "红树原木" },
  "Mangrove Roots": { nbt: "mangrove_roots", zh: "红树根" },
  "Netherrack": { nbt: "netherrack", zh: "下界岩" },
  "Nether Brick": { nbt: "nether_bricks", zh: "下界砖块" },
  "Nether Brick Slab": { nbt: "nether_brick_slab", zh: "下界砖台阶" },
  "Magma Block": { nbt: "magma_block", zh: "岩浆块" },
  "Red Nether Bricks": { nbt: "red_nether_bricks", zh: "红色下界砖块" },
  "Red Nether Brick Slab": { nbt: "red_nether_brick_slab", zh: "红色下界砖台阶" },
  "White Terracotta": { nbt: "white_terracotta", zh: "白色陶瓦" },
  "Calcite": { nbt: "calcite", zh: "方解石" },
  "Cherry Planks": { nbt: "cherry_planks", zh: "樱花木板" },
  "Cherry Slab": { nbt: "cherry_slab", zh: "樱花木台阶" },
  "Cherry Log (vertical)": { nbt: "cherry_log", zh: "樱花原木" },
  "Stripped Cherry Log (vertical)": { nbt: "stripped_cherry_log", zh: "去皮樱花原木" },
  "Cherry Pressure Plate": { nbt: "cherry_pressure_plate", zh: "樱花木压力板" },
  "Orange Terracotta": { nbt: "orange_terracotta", zh: "橙色陶瓦" },
  "Magenta Terracotta": { nbt: "magenta_terracotta", zh: "品红色陶瓦" },
  "Light Blue Terracotta": { nbt: "light_blue_terracotta", zh: "淡蓝色陶瓦" },
  "Yellow Terracotta": { nbt: "yellow_terracotta", zh: "黄色陶瓦" },
  "Lime Terracotta": { nbt: "lime_terracotta", zh: "黄绿色陶瓦" },
  "Pink Terracotta": { nbt: "pink_terracotta", zh: "粉红色陶瓦" },
  "Stripped Cherry Log (horizontal)": { nbt: "stripped_cherry_log", zh: "去皮樱花原木" },
  "Stripped Cherry Wood": { nbt: "stripped_cherry_wood", zh: "去皮樱花木" },
  "Gray Terracotta": { nbt: "gray_terracotta", zh: "灰色陶瓦" },
  "Tuff": { nbt: "tuff", zh: "凝灰岩" },
  "Cherry Log (horizontal)": { nbt: "cherry_log", zh: "樱花原木" },
  "Cherry Wood": { nbt: "cherry_wood", zh: "樱花木" },
  "Light Gray Terracotta": { nbt: "light_gray_terracotta", zh: "淡灰色陶瓦" },
  "Waxed Exposed Copper": { nbt: "waxed_exposed_copper", zh: "斑驳的涂蜡铜块" },
  "Waxed Exposed Cut Copper Slab": { nbt: "waxed_exposed_cut_copper_slab", zh: "斑驳的涂蜡切制铜台阶" },
  "Mud Bricks": { nbt: "mud_bricks", zh: "泥砖" },
  "Mud Brick Slab": { nbt: "mud_brick_slab", zh: "泥砖台阶" },
  "Cyan Terracotta": { nbt: "cyan_terracotta", zh: "青色陶瓦" },
  "Mud": { nbt: "mud", zh: "泥巴" },
  "Purple Terracotta": { nbt: "purple_terracotta", zh: "紫色陶瓦" },
  "Blue Terracotta": { nbt: "blue_terracotta", zh: "蓝色陶瓦" },
  "Brown Terracotta": { nbt: "brown_terracotta", zh: "棕色陶瓦" },
  "Dripstone Block": { nbt: "dripstone_block", zh: "滴水石块" },
  "Pointed Dripstone": { nbt: "pointed_dripstone", zh: "滴水石锥" },
  "Green Terracotta": { nbt: "green_terracotta", zh: "绿色陶瓦" },
  "Red Terracotta": { nbt: "red_terracotta", zh: "红色陶瓦" },
  "Black Terracotta": { nbt: "black_terracotta", zh: "黑色陶瓦" },
  "Crimson Nylium": { nbt: "crimson_nylium", zh: "绯红菌岩" },
  "Crimson Stem": { nbt: "crimson_stem", zh: "绯红菌柄" },
  "Stripped Crimson Stem": { nbt: "stripped_crimson_stem", zh: "去皮绯红菌柄" },
  "Crimson Planks": { nbt: "crimson_planks", zh: "绯红木板" },
  "Crimson Slab": { nbt: "crimson_slab", zh: "绯红木台阶" },
  "Crimson Pressure Plate": { nbt: "crimson_pressure_plate", zh: "绯红木压力板" },
  "Crimson Hyphae": { nbt: "crimson_hyphae", zh: "绯红菌核" },
  "Stripped Crimson Hyphae": { nbt: "stripped_crimson_hyphae", zh: "去皮绯红菌核" },
  "Warped Nylium": { nbt: "warped_nylium", zh: "诡异菌岩" },
  "Waxed Oxidized Copper": { nbt: "waxed_oxidized_copper", zh: "氧化的涂蜡铜块" },
  "Waxed Oxidized Cut Copper Slab": { nbt: "waxed_oxidized_cut_copper_slab", zh: "氧化的涂蜡切制铜台阶" },
  "Warped Stem": { nbt: "warped_stem", zh: "诡异菌柄" },
  "Stripped Warped Stem": { nbt: "stripped_warped_stem", zh: "去皮诡异菌柄" },
  "Warped Planks": { nbt: "warped_planks", zh: "诡异木板" },
  "Warped Slab": { nbt: "warped_slab", zh: "诡异木台阶" },
  "Waxed Weathered Copper": { nbt: "waxed_weathered_copper", zh: "锈蚀的涂蜡铜块" },
  "Waxed Weathered Cut Copper Slab": { nbt: "waxed_weathered_cut_copper_slab", zh: "锈蚀的涂蜡切制铜台阶" },
  "Warped Pressure Plate": { nbt: "warped_pressure_plate", zh: "诡异木压力板" },
  "Warped Hyphae": { nbt: "warped_hyphae", zh: "诡异菌核" },
  "Stripped Warped Hyphae": { nbt: "stripped_warped_hyphae", zh: "去皮诡异菌核" },
  "Warped Wart Block": { nbt: "warped_wart_block", zh: "诡异疣块" },
  "Deepslate": { nbt: "deepslate", zh: "深板岩" },
  "Cobbled Deepslate": { nbt: "cobbled_deepslate", zh: "深板岩圆石" },
  "Cobbled Deepslate Slab": { nbt: "cobbled_deepslate_slab", zh: "深板岩圆石台阶" },
  "Block Of Raw Iron": { nbt: "raw_iron_block", zh: "粗铁块" },
  "Glow Lichen": { nbt: "glow_lichen", zh: "发光地衣" },
  "Verdant Froglight": { nbt: "verdant_froglight", zh: "青翠蛙明灯" },
};
